version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: 'workflow-templates/'
    ignore:
      # can not check private repo's from this public one... therefore ignoring it
      - depdendency-name: 'myplant-io/github-actions/*'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
  - package-ecosystem: 'github-actions'
    directory: 'optional-workflows/'
    ignore:
      # can not check private repo's from this public one... therefore ignoring it
      - depdendency-name: 'myplant-io/github-actions/*'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
  - package-ecosystem: 'github-actions'
    directory: '/'
    ignore:
      # can not check private repo's from this public one... therefore ignoring it
      - depdendency-name: 'myplant-io/github-actions/*'
    schedule:
      interval: 'daily'
