name: 'Auto-Update'
description: 'Auto-Update of github actions'
outputs:
  ref:
    description: 'Ref'
    value: ${{ steps.ref.outputs.ref }}
runs:
  using: 'composite'
  steps:
    - run: echo ${{ github.ref }}
      shell: bash
    - id: ref
      run: echo "ref=${{ github.ref }}" >> ${GITHUB_OUTPUT}
      shell: bash
