###
# GitHub action that updates github actions from the template repository.
#
# Created by: Nikolaus Krismer
###
name: Update GitHub actions

on:
  pull_request_target:
  workflow_dispatch:

jobs:
  updateGitHubActions:
    name: "Job: Update GH actions"
    # if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    concurrency:
      group: "distribute_${{ github.ref }}"
      cancel-in-progress: false

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout github actions repo
        uses: actions/checkout@v3

      - name: Checkout github actions repository
        uses: myplant-io/.github@v0.1.0

      - name: Checkout github actions repo
        uses: actions/checkout@v3
        working-directory: .github/workflows
        with:
          repository: myplant-io/.github
          token: ${{ secrets.CI_PAT }}
          path: remote

      - name: Move relevant github actions in place
        working-directory: .github/workflows
        run: |
          mv remote/common-actions-update.yml actions-update.yaml
          mv remote/common-merge.yml merge.yaml
          mv remote/gradle-dependency-check.yml dependency-check.yaml
          mv remote/gradle-deploy.yml deploy.yaml
          mv remote/gradle-sonarqube.yml sonarqube.yaml
          mv remote/gradle-test.yml test.yaml

      - name: Move relevant github actions in place
        working-directory: .github/workflows
        run: |
          git commit -m "chore: auto-updating github actions to latest version"

      - name: Push changes
        uses: ad-m/github-push-action@0.6.0
        with:
          force_with_lease: true
