name: GitLeaks

on:
  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    name: 'Job: gitleaks'
    if: github.actor != 'dependabot[bot]'
    runs-on: [self-hosted-standard]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
