version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
  - package-ecosystem: 'github-actions'
    directory: '/'
    allow:
      - dependency-name: 'myplant-io/.github'
    schedule:
      interval: 'daily'
