name: Sonarqube

on:
  # see https://github.com/dependabot/dependabot-core/issues/3253 why this is pull_request_taget and not pull_request
  pull_request_target:
    branches: [develop]
  push:
    branches: [master, develop, release/**, hotfix/**]
  workflow_dispatch:

env:
  GRADLE_TASK: "sonarqube -x test"
  JAVA_VERSION: 11

jobs:
  sonarqube:
    name: "Job: Sonarqube"
    runs-on: ubuntu-latest

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set env 'BRANCH_NAME'
        run: echo BRANCH_NAME=${GITHUB_REF/refs\/heads\//} >> ${GITHUB_ENV}

      - name: Set env 'SHA'
        run: echo SHA=$(echo ${GITHUB_SHA} | cut -c1-7) >> ${GITHUB_ENV}

      - name: Set env 'VERSION' to SHA (for untagged deployments)
        if: startsWith(github.ref, 'refs/tags/') != true
        run: echo VERSION=${{ env.SHA }} >> ${GITHUB_ENV}

      - name: Set env 'TAG' (for tagged deployment)
        if: startsWith(github.ref, 'refs/tags/')
        run: echo TAG=${GITHUB_REF/refs\/tags\//} >> ${GITHUB_ENV}

      - name: Set 'VERSION' (for tagged deployment)
        if: startsWith(github.ref, 'refs/tags/')
        run: echo VERSION=${TAG#v} >> ${GITHUB_ENV}

      - name: Log details
        run: |
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REPO: ${{ github.event.repository.name }}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "TAG: ${{ env.TAG }}"
          echo "VERSION: ${{ env.VERSION }}"
          echo "sonar.branch.name: ${{ env.BRANCH_NAME }}"
          echo "sonar.github.repository: ${{ github.repository }}"
          echo "sonar.pullrequest.base: ${{ github.base_ref }}"
          echo "sonar.pullrequest.branch: ${{ github.head_ref }}"
          echo "sonar.pullrequest.key: ${{ github.event.number }}"

      - name: Prepare gradle properties
        run: printf "\n$GRADLE_PROPS" >> gradle.properties
        env:
          GRADLE_PROPS: ${{ secrets.GRADLE_PROPERTIES }}

      - name: Prepare Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Sonarqube with gradle
        uses: eskatos/gradle-command-action@v1
        if: github.event_name != 'pull_request'
        with:
          arguments: ${{ env.GRADLE_TASK }} -Pversion=${{ env.VERSION }}

      - name: Sonarqube with gradle (on PR)
        uses: eskatos/gradle-command-action@v1
        if: github.event_name == 'pull_request'
        with:
          arguments: |
            ${{ env.GRADLE_TASK }} -Pversion=${{ env.VERSION }}
              -Dsonar.pullrequest.github.endpoint=https://api.github.com
              -Dsonar.pullrequest.github.repository=${{ github.repository }}
              -Dsonar.pullrequest.base=${{ github.base_ref }}
              -Dsonar.pullrequest.branch=${{ github.head_ref }}
              -Dsonar.pullrequest.key=${{ github.event.number }}
