name: Test and validate

on:
  # see https://github.com/dependabot/dependabot-core/issues/3253 why this is pull_request_taget and not pull_request
  pull_request_target:
    branches: [develop]
  workflow_dispatch:

env:
  GRADLE_TASK: "test"

jobs:
  testAndValidate:
    name: "Job: Test and validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout git repository
        if: startsWith(github.event_name , 'pull_request') == false
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Checkout git repository (on PR)
        if: startsWith(github.event_name , 'pull_request')
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set env 'VERSION' to SHA
        run: echo VERSION="${{ env.SHA }}" >> ${GITHUB_ENV}

      - name: Log details
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "VERSION: ${{ env.VERSION }}"

      - name: Prepare gradle properties
        run: printf "\n$GRADLE_PROPS" >> gradle.properties
        env:
          GRADLE_PROPS: ${{ secrets.GRADLE_PROPERTIES }}

      - name: Prepare java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java-version }}

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Test with gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ${{ env.GRADLE_TASK }} -Pversion=${{ env.VERSION }}

      - name: Compress test report folders
        if: ${{ failure() }}
        id: report-dir
        run: |
          folders=$(./gradlew tasks --all | grep ":assemble" | cut -d: -f1 | sort -u | sed 's#$#/build/reports/tests#' | xargs)
          zip -qq -r test-results.zip $folders

      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: test-results.zip
