###
# GitHub action that runs tests on the code.
#
# Prerequisites:
#  - ".github/workflow-config.env" exists
#
# Created by: Daniel Hons, Nikolaus Krismer
###
name: Validate and test

on:
  # see https://github.com/dependabot/dependabot-core/issues/3253 why this is pull_request_target and not pull_request
  pull_request_target:
    branches: [develop, release/**, bugfix/**, hotfix/**]
    paths-ignore:
      - '.github/workflows/*auto-update*'
  workflow_dispatch:

jobs:
  validateAndTest:
    name: 'Job: Validate and test'
    runs-on: [self-hosted-standard]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout git repository
        if: startsWith(github.event_name , 'pull_request') == false
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Checkout git repository (on PR)
        if: startsWith(github.event_name , 'pull_request')
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check workflow config file existence
        uses: andstor/file-existence-action@v2
        with:
          fail: true
          files: '.github/workflow-config.env'

      - name: Load workflow config (.env file)
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.github/workflow-config.env'

      - name: Set env 'SHA'
        if: startsWith(github.event_name , 'pull_request') == false
        run: echo SHA=$(echo ${GITHUB_SHA} | cut -c1-7) >> ${GITHUB_ENV}

      - name: Set env 'SHA' (on PR)
        if: startsWith(github.event_name , 'pull_request')
        run: echo SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7) >> ${GITHUB_ENV}

      - name: Set env 'VERSION' to SHA
        run: echo VERSION="${{ env.SHA }}" >> ${GITHUB_ENV}

      - name: Log details
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "VERSION: ${{ env.VERSION }}"

      - name: Prepare gradle properties
        run: printf "\n$GRADLE_PROPS" >> gradle.properties
        env:
          GRADLE_PROPS: ${{ secrets.GRADLE_PROPERTIES }}

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Prepare gradle
        uses: gradle/gradle-build-action@v2

      - name: Get java version from gradle
        run: echo "JAVA_VERSION=$(./gradlew -q :javaVersion -Dorg.gradle.java.home=$JAVA_HOME_17_X64 | tail -n 1)" >> ${GITHUB_ENV}

      - name: Prepare java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Configure AWS credentials (to enable test to download containers)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_USER }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: aws-login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Test with gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ env.GRADLE_TEST_TASK }} -Pversion=${{ env.VERSION }}

      - name: Test reporting
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report
          path: '**/build/test-results/test/TEST-*.xml'
          reporter: java-junit

      - name: Determine number of gradle (sub)projects
        id: gradle-project-stats
        if: failure()
        run: echo "project-count=$(./gradlew tasks --all | grep ':assemble' | cut -d ':' -f 1 | wc -l)" >> ${GITHUB_OUTPUT}

      - name: Compress and upload test report folders
        if: failure() && steps.gradle-project-stats.outputs.project-count == '0'
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: 'build/reports/tests'

      - name: Compress test report folders (for multirepo)
        if: failure() && steps.gradle-project-stats.outputs.project-count != '0'
        run: |
          folders=$(./gradlew tasks --all | grep ':assemble' | cut -d ':' -f 1 | sort -u | sed 's#$#/build/reports/tests#' | xargs)
          zip -qq -r test-results.zip $(echo ${folders})

      - name: Upload test results (for multirepo)
        if: failure() && steps.gradle-project-stats.outputs.project-count != '0'
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: test-results.zip
