name: Dependency check

on:
  schedule:
    # at 00:00 every sunday (on the default branch - develop)
    - cron:  '0 0 * * SUN'
  push:
    branches: [master]
  workflow_dispatch:

env:
  GRADLE_TASK: 'cyclonedx dependencyCheckAnalyze'
  JAVA_VERSION: 11

jobs:
  dependencyCheck:
    name: 'Job: Dependency check'
    runs-on: ubuntu-latest

    steps:
      - name: Set git to use LF
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set env 'BRANCH_NAME'
        shell: bash
        run: echo BRANCH_NAME=${GITHUB_REF/refs\/heads\//} >> ${GITHUB_ENV}

      - name: Set env 'SHA'
        shell: bash
        run: echo SHA=$(echo ${GITHUB_SHA} | cut -c1-7) >> ${GITHUB_ENV}

      - name: Set 'VERSION' to SHA
        shell: bash
        run: echo VERSION=${{ env.SHA }} >> ${GITHUB_ENV}

      - name: Log details
        shell: bash
        run: |
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REPO: ${{ github.event.repository.name }}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "VERSION: ${{ env.VERSION }}"
          echo "depdendency.track.projectname: ${GITHUB_REPOSITORY}"
          echo "depdendency.track.projectversion: ${{ env.BRANCH_NAME }}"s

      - name: Prepare gradle properties
        shell: bash
        env:
          GRADLE_PROPS: ${{ secrets.GRADLE_PROPERTIES }}
        run: printf "\n$GRADLE_PROPS" >> gradle.properties

      - name: Prepare Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Dependency check with gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: |
            ${{ env.GRADLE_TASK }} -Pversion=${{ env.VERSION }}
            -Pcyclonedx.includeBomSerialNumber=false

      - name: Post process dependency check bom
        shell: bash
        run: sed -i "s/type=jar//g" build/reports/bom.xml

      - name: Publish dependency check result to tracker
        id: upload-dependency-track
        uses: ./.github/actions/upload-dependency-track
        with:
          apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          bomfilename: 'build/reports/bom.xml'
          projectname: ${GITHUB_REPOSITORY}
          projectversion: ${{ env.BRANCH_NAME }}
