name: Test and validate

on:
  # see https://github.com/dependabot/dependabot-core/issues/3253 why this is pull_request_taget and not pull_request
  pull_request_target:
    branches: [develop]
  workflow_dispatch:

env:
  GRADLE_TASK: "test"
  JAVA_VERSION: 11
  REPORT_DIR: auto

jobs:
  testAndValidate:
    name: "Job: Test and validate"
    runs-on: ubuntu-latest

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout git repository
        if: startsWith(github.event_name , 'pull_request') == false
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Checkout git repository (on PR)
        if: startsWith(github.event_name , 'pull_request')
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set env 'VERSION' to SHA (for untagged deployments)
        if: startsWith(github.ref, 'refs/tags/') == false
        run: echo VERSION="${{ env.SHA }}" >> ${GITHUB_ENV}

      - name: Set env 'REPORT_DIR'
        if: env.REPORT_DIR == 'auto'
        run: echo REPORT_DIR="build/reports/tests/" >> ${GITHUB_ENV}

      - name: Log details
        run: |
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REPO: ${{ github.event.repository.name }}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "REPORT_DIR: ${{ env.REPORT_DIR }}"
          echo "VERSION: ${{ env.VERSION }}"

      - name: Prepare Gradle properties
        run: printf "\n$GRADLE_PROPS" >> gradle.properties
        env:
          GRADLE_PROPS: ${{ secrets.GRADLE_PROPERTIES }}

      - name: Prepare Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with gradle (incl. test and sonar)
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ${{ env.GRADLE_TASK }} -Pversion=${{ env.VERSION }}

      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: ${{ env.REPORT_DIR }}
