version: 2
registries:
  maven-myplant-nexus:
    type: maven-repository
    url: https://nexus-dev.myplant.io/repository/myplantpy
    username: ${{secrets.NEXUS_USER_RO}}
    password: ${{secrets.NEXUS_PW_RO}}
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    registries:
      - maven-myplant-nexus
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    insecure-external-code-execution: allow
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
