###
# GitHub action that creates a Software-Bill-of-Material (SBOM) and pushes the
# result to the myplant dependency tracker (dependency-dev.myplant.io).
#
# Prerequisites:
#  - ".github/workflow-config.env" exists
#
# Created by: Nikolaus Krismer and Nikolaus Brunner
###
name: Dependency check

on:
  schedule:
    # at 00:00 every sunday (on the default branch - develop)
    - cron: '0 0 * * SUN'
  push:
    branches: [main, master]
  repository_dispatch:
    types: [dependencyCheck]
  workflow_dispatch:

jobs:
  setup:
    name: 'Job: Python setup'
    outputs:
    pythonVersionFile: ${{steps.set_outputs.outputs.pythonVersionFile}}

    steps:
      - name: Check python version determination (pyproject.toml)
        id: check_file_pyproject
        uses: andstor/file-existence-action@v3
        with:
          fail: false
          files: 'pyproject.toml'

      - name: Use pyproject.toml as python version file
        if: steps.check_file_pyproject.outputs.files_exists == 'true'
        run: echo PYTHON_VERSION_FILE="pyproject.toml" >> ${GITHUB_ENV}

      - name: Check python version determination (.python-version)
        if: steps.check_file_pyproject.outputs.files_exists == 'false'
        id: check_file_python_version
        uses: andstor/file-existence-action@v3
        with:
          fail: false
          files: '.python-version'

      - name: Use pyproject.toml as python version file
        if: steps.check_file_python_version.outputs.files_exists == 'true'
        run: echo PYTHON_VERSION_FILE=".python-version" >> ${GITHUB_ENV}

      - name: Check python version determination
        if: steps.check_file_pyproject.outputs.files_exists == 'false' &&  steps.check_file_python_version.outputs.files_exists == 'false'
        run: |
          echo "::error Either pyproject.toml or .python-version must exists (and contain a python version number)"
          exit 1

      - id: set_outputs
        name: Set python version file
        run: echo "::set-output name=pythonVersionFile::${{ env.PYTHON_VERSION_FILE}}"

  dependencyCheck:
    name: 'Job: Dependency check'
    needs: ['setup']
    runs-on: [self-hosted-standard]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout git repository
        uses: actions/checkout@v4
        if: github.event_name != 'repository_dispatch'
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Check workflow config file existence
        uses: andstor/file-existence-action@v3
        with:
          fail: true
          files: '.github/workflow-config.env'

      - name: Load workflow config (.env file)
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.github/workflow-config.env'

      - name: Check python version determination (pyproject.toml)
        id: check_file_pyproject
        uses: andstor/file-existence-action@v3
        with:
          fail: false
          files: 'pyproject.toml'

      - name: Check python version determination (.python-version)
        if: steps.check_file_pyproject.outputs.files_exists == 'false'
        id: check_file_python_version
        uses: andstor/file-existence-action@v3
        with:
          fail: false
          files: '.python-version'

      - name: Check python version determination
        if: steps.check_file_pyproject.outputs.files_exists == 'false' &&  steps.check_file_python_version.outputs.files_exists == 'false'
        run: |
          echo "::error Either pyproject.toml or .python-version must exists (and contain a python version number)"
          exit 1

      - name: Checkout git repository (for dispatched runs)
        uses: actions/checkout@v4
        if: github.event_name == 'repository_dispatch'
        with:
          fetch-depth: 0
          ref: '${{ github.event.client_payload.branch }}'

      - name: Set env 'COMPONENT_NAME'
        if: env.COMPONENT_NAME == 'auto'
        run: echo COMPONENT_NAME="${GITHUB_REPOSITORY#*/}" >> ${GITHUB_ENV}

      - name: Set env 'BRANCH_NAME'
        run: echo BRANCH_NAME="${GITHUB_REF/refs\/heads\//}" >> ${GITHUB_ENV}

      - name: Set env 'SHA'
        run: echo SHA="$(echo ${GITHUB_SHA} | cut -c1-7)" >> ${GITHUB_ENV}

      - name: Set 'VERSION' to SHA
        run: echo VERSION="${{ env.SHA }}" >> ${GITHUB_ENV}

      - uses: kenchan0130/actions-system-info@v1.2.1
        if: env.VERBOSE_LOGGING == 'true'
        id: system-info

      - name: Log dependency tracker context
        if: env.VERBOSE_LOGGING == 'true'
        run: |
          echo "dependency.track.projectname: ${{ env.COMPONENT_NAME }}"
          echo "dependency.track.projectversion: ${{ env.BRANCH_NAME }}"

      - name: Log env context
        if: env.VERBOSE_LOGGING == 'true'
        run: echo $JSON | jq
        env:
          JSON: ${{ toJSON(env) }}

      - name: Log github context
        if: env.VERBOSE_LOGGING == 'true'
        run: echo $JSON | jq
        env:
          JSON: ${{ toJSON(github) }}

      - name: Log system details
        if: env.VERBOSE_LOGGING == 'true'
        run: |
          echo "os: ${{ runner.os }}"
          echo "host.cpu-model: ${{ steps.system-info.outputs.cpu-model }}"
          echo "host.cpu-core: ${{ steps.system-info.outputs.cpu-core }}"
          echo "host.name: ${{ steps.system-info.outputs.hostname }}"
          echo "os.name: ${{ steps.system-info.outputs.name }}"
          echo "os.kernel.release: ${{ steps.system-info.outputs.kernel-release }}"
          echo "os.kernel.version: ${{ steps.system-info.outputs.kernel-version }}"
          echo "os.platform: ${{ steps.system-info.outputs.platform }}"
          echo "os.release: ${{ steps.system-info.outputs.release }}"

      - name: Check poetry existence
        id: check_poetry
        uses: andstor/file-existence-action@v3
        with:
          fail: false
          files: 'poetry.lock'

      - name: Prepare python (with pip)
        if: steps.check_poetry.outputs.files_exists == 'false'
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version-file: ${{fromJSON(needs.setup.outputs.pythonVersionFile)}}

      - name: Prepare python (with poetry)
        if: steps.check_poetry.outputs.files_exists == 'true'
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          python-version-file: ${{fromJSON(needs.setup.outputs.pythonVersionFile)}}

      - name: Check poetry file existence
        uses: andstor/file-existence-action@v3
        id: check-poetry-lock
        with:
          files: 'poetry.lock'

      - name: CycloneDX Python Generate SBOM with poetry
        uses: myplant-io/github-actions/python-generate-sbom@v1
        if: steps.check-poetry-lock.outputs.files_exists == 'true'
        with:
          input: './'
          output: './bom.xml'
          type: 'poetry'

      - name: CycloneDX Python Generate SBOM with pip
        uses: myplant-io/github-actions/python-generate-sbom@v1
        if: steps.check-poetry-lock.outputs.files_exists == 'false'
        with:
          input: './requirements.txt'
          output: './bom.xml'
          type: 'requirements'

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: SBOM
          path: './bom.xml'

      - name: Publish dependency check result to tracker
        id: upload-dependency-track
        uses: myplant-io/github-actions/upload-dependency-track@v1
        with:
          apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          bomfilename: './bom.xml'
          projectname: ${{ env.COMPONENT_NAME }}
          projectversion: ${{ env.BRANCH_NAME }}
