version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    allow:
      - dependency-type: 'production'
    ignore:
      - dependency-name: '@types/node'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
