###
# GitHub action that runs tests on the code.
#
# Prerequisites:
#  - ".github/workflow-config.env" exists
#
# Created by: Nikolaus Krismer
###
name: Validate and test

on:
  # see https://github.com/dependabot/dependabot-core/issues/3253 why this is pull_request_target and not pull_request
  pull_request_target:
    branches: [develop, release/**, bugfix/**, hotfix/**]
    paths-ignore:
      - '.github/workflows/*auto-update*'
  workflow_dispatch:

jobs:
  validateAndTest:
    name: 'Job: Validate and test'
    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout git repository
        if: startsWith(github.event_name , 'pull_request') == false
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Checkout git repository (on PR)
        if: startsWith(github.event_name , 'pull_request')
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Log details
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"

      - name: Prepare node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Add registry credentials
        run: echo YARN_NPM_AUTH_TOKEN=${NPM_REGISTRY_AUTH#"//npm.pkg.github.com/:_authToken="} >> ${GITHUB_ENV}
        env:
          NPM_REGISTRY_AUTH: ${{ secrets.NPM_REGISTRY_AUTH }}

      - name: Create/restore cache for webpack
        uses: actions/cache@v3
        id: webpack-cache
        with:
          path: '.cache'
          key: ${{ runner.os }}-webpack-${{ env.VERSION }}
          restore-keys: ${{ runner.os }}-webpack-

      - name: Create/restore cache for yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Determine if config needs to be generated
        id: npm_script_check
        run: echo generate_config_exists=$(npm run | grep 'generate:config' | wc -l) >> ${GITHUB_OUTPUT}

      - name: Generate config files
        if: steps.npm_script_check.outputs.generate_config_exists != 0
        run: yarn generate:config

      - name: Run validations
        run: yarn validate

      - name: Run tests
        run: yarn test
