###
# GitHub action that creates a Software-Bill-of-Material (SBOM) and pushes the
# result to the myplant dependency tracker (dependency-dev.myplant.io).
#
# Prerequisites:
#  - ".github/workflow-config.env" exists
#
# Created by: Nikolaus Krismer
###
name: Dependency check

on:
  schedule:
    # at 00:00 every sunday (on the default branch - develop)
    - cron: "0 0 * * SUN"
  push:
    branches: [main, master]
  repository_dispatch:
    types: [dependencyCheck]
  workflow_dispatch:

jobs:
  dependencyCheck:
    name: "Job: Dependency check"
    runs-on: [self-hosted, linux]
    concurrency:
      group: "dependencyCheck_${{ github.ref }}"
      cancel-in-progress: true

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout git repository
        uses: actions/checkout@v3
        if: github.event_name != 'repository_dispatch'
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Checkout git repository (for dispatched runs)
        uses: actions/checkout@v3
        if: github.event_name == 'repository_dispatch'
        with:
          fetch-depth: 0
          ref: "${{ github.event.client_payload.branch }}"

      - name: Check workflow config file existence
        uses: andstor/file-existence-action@v1
        with:
          allow_failure: true
          files: ".github/workflow-config.env"

      - name: Load workflow config (.env file)
        uses: cardinalby/export-env-action@v1
        with:
          envFile: ".github/workflow-config.env"

      - name: Checkout github actions repository
        uses: actions/checkout@v3
        with:
          repository: myplant-io/github-actions
          ref: v0.6.1
          token: ${{ secrets.CI_PAT }}
          path: .github/actions

      - name: Set env 'COMPONENT_NAME'
        if: env.COMPONENT_NAME == 'auto'
        run: echo COMPONENT_NAME="${GITHUB_REPOSITORY#*/}" >> ${GITHUB_ENV}

      - name: Set env 'BRANCH_NAME'
        if: github.event_name != 'repository_dispatch'
        run: echo BRANCH_NAME="${GITHUB_REF#refs/heads/}" >> ${GITHUB_ENV}

      - name: Set env 'BRANCH_NAME' (for dispatched runs)
        if: github.event_name == 'repository_dispatch'
        run: echo BRANCH_NAME="${{ github.event.client_payload.branch }}" >> ${GITHUB_ENV}

      - name: Log details
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "VERSION: ${{ env.VERSION }}"
          echo "dependency.track.projectname: ${{ env.COMPONENT_NAME }}"
          echo "dependency.track.projectversion: ${{ env.BRANCH_NAME }}"

      - name: Prepare node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Add registry credentials
        run: echo YARN_NPM_AUTH_TOKEN=${NPM_REGISTRY_AUTH#"//npm.pkg.github.com/:_authToken="} >> $GITHUB_ENV
        env:
          NPM_REGISTRY_AUTH: ${{ secrets.NPM_REGISTRY_AUTH }}

      - name: Create/restore cache for yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install html report
        run: npm install --no-package-lock --no-save npm-audit-html

      - name: Perform audit
        continue-on-error: true
        run: yarn npm audit --environment production --severity ${SECURITY_LEVEL} --json | npx --no-install npm-audit-html

      - name: Upload audit report artifact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: audit-report
          path: npm-audit.html
## Skipping SBOM part for now (no support for yarn2 yet)
#      - name: Install cyclonedx
#        run: npm install --no-package-lock --no-save @cyclonedx/cyclonedx-npm
#
#      - name: Create SBOM using cyclonedx
#        run: npx @cyclonedx/cyclonedx-npm --output-file bom.xml

#      - name: Upload SBOM artifact
#        uses: actions/upload-artifact@v3
#        with:
#          if-no-files-found: error
#          name: SBOM
#          path: bom.xml

#      - name: Publish dependency check result to tracker
#        id: upload-dependency-track
#        uses: ./.github/actions/upload-dependency-track
#        with:
#          apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
#          bomfilename: "./bom.xml"
#          projectname: ${{ env.COMPONENT_NAME }}
#          projectversion: ${{ env.BRANCH_NAME }}

