###
# Creates a comment on a pull request that summarizes the changes in the PR.
#
# Created by: Simon Schafferer, Gernot Hummer
###
name: AI Code Review

on:
  pull_request:

jobs:
  pr-review:
    name: 'Job: AI Review'
    runs-on: [self-hosted-standard]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine changes
        uses: GrantBirki/git-diff-action@v2
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: 'true'

      - name: Read diff
        id: read-diff-file
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "file-content<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$(cat ${{ steps.git-diff-action.outputs.raw-diff-path }})" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Review changes with AI
        id: perform_ai_review
        uses: myplant-io/github-actions/ai-code-review@feat/add-ai-code-review
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_USER }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET }}
          aws-region: us-east-1
          git-diff-output: ${{ steps.read-diff-file.outputs.file-content }}
          openai-api-key: ${{ secrets.openai_api_key }}
          pr-description: ${{ github.event.pull_request.body }}
          pr-title: ${{ github.event.pull_request.title }}

      - name: Add PR review comment thollander
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ${{ steps.perform_ai_review.outputs.message }}
