###
# Creates a comment on a pull request that summarizes the changes in the PR.
#
# Created by: Simon Schafferer, Gernot Hummer
###
name: AI Code Review

on:
  pull_request:

jobs:
  pr-review:
    name: 'Job: AI Review'
    runs-on: [self-hosted-standard]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine changes
        uses: GrantBirki/git-diff-action@v2
        id: git_diff_action
        with:
          raw_diff_file_output: diff.txt
          file_output_only: 'true'

      - name: Read changes from file
        id: read_diff_file
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "file_content<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$(cat ${{ steps.git_diff_action.outputs.raw-diff-path }})" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Review changes with AI
        id: perform_ai_review
        uses: myplant-io/github-actions/ai-code-review@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_STG_USER_AI }}
          aws_secret_access_key: ${{ secrets.AWS_STG_SECRET_AI }}
          aws_region: us-east-1
          git_diff_output: ${{ steps.read_diff_file.outputs.file_content }}
          openai_api_key: ${{ secrets.openai_api_key }}
          pr_description: ${{ github.event.pull_request.body }}
          pr_title: ${{ github.event.pull_request.title }}

      - name: Add PR review comment thollander
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ${{ steps.perform_ai_review.outputs.message }}
          comment-tag: ai_code_review
          reactions: eyes
