name: Validate workflows

on:
  pull_request:

jobs:
  lint:
    name: "Job: Validate workflows"
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup node.js
        uses: actions/setup-node@v7
        with:
          package-manager-cache: false

      - name: Install dependencies
        run: npm install --no-save prettier

      - name: Check workflows with prettier
        run: npx prettier --check .
