name: Validate Workflows

on:
  pull_request:

jobs:
  validate:
    name: 'Job: Validate workflows'
    runs-on: [self-hosted-standard]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate workflows with prettier
        uses: actionsx/prettier@v2
        with:
          args: --check .
