name: Validate workflows

on:
  pull_request:

jobs:
  validate:
    name: 'Job: Validate workflows'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate workflows with prettier
        uses: actionsx/prettier@v3
        with:
          args: --check .
